### PR TITLE
Add a spec file to support builds

### PR DESCRIPTION
**Pull request by sairameshv**
In order to add an rpm, a spec file is required according to the slack discussion [here](https://redhat-internal.slack.com/archives/CB95J6R4N/p1721712308796239?thread_ts=1719487149.865679&cid=CB95J6R4N) and hence the PR

/cc @harche @mrunalp

### CODE REVIEW

**Comment by joepvd** [comment]
@harche Think it reduces headaches if we merge this. Then the rpm will become available in CI and OSE repos for 4.18. RHCOS can start to include this rpm when that passes testing. imho this can have an unhold :)

**Comment by harche** [comment]
> @harche Think it reduces headaches if we merge this. Then the rpm will become available in CI and OSE repos for 4.18. RHCOS can start to include this rpm when that passes testing. imho this can have an unhold :)

Sure, thanks. 
/hold cancel
/lgtm

**Pull request merged**
